aleph/alerts/__init__.py
import logging
from urllib import urlencode
from flask import request, render_template, current_app

from aleph.core import get_config, db, celery
from aleph.model import Role, Alert
from aleph.notify import notify_role
from aleph.search.documents import documents_query
from aleph.search.documents import execute_documents_alert_query

log = logging.getLogger(__name__)


@celery.task()
def check_alerts():
    for role_id, in Role.notifiable():
        with current_app.test_request_context('/'):
            role = Role.by_id(role_id)
            request.auth_role = role
            request.logged_in = True
            # FIXME: can't re-gain access to implicit oauth rules.
            # -> https://github.com/pudo/aleph/issues/14
            request.auth_roles = [Role.system(Role.SYSTEM_USER),
                                  Role.system(Role.SYSTEM_GUEST),
                                  role.id]
            check_role_alerts(role)


def make_document_query(alert):
    qs = {'dq': alert.query.get('q')}
    qs.update(alert.query)
    args = []
    for k, vs in qs.items():
        if isinstance(vs, (list, tuple, set)):
            for v in vs:
                args.append((k, v))
        else:
            args.append((k, vs))
    return urlencode(args)


def check_role_alerts(role):
    alerts = Alert.by_role(role).all()
    if not len(alerts):
        return
    log.info('Alerting %r, %d alerts...', role, len(alerts))
    for alert in alerts:
        q = documents_query(alert.query, newer_than=alert.notified_at)
        results = execute_documents_alert_query(alert.query, q)
        if results['total'] == 0:
            continue
        log.info('Found: %d new results for: %r', results['total'],
                 alert.query)
        alert.update()
        try:
            subject = '%s (%s new results)' % (alert.label, results['total'])
            html = render_template('alert.html', alert=alert, results=results,
                                   role=role, qs=make_document_query(alert),
                                   app_title=get_config('APP_TITLE'),
                                   app_url=get_config('APP_BASEURL'))
            notify_role(role, subject, html)
        except Exception as ex:
            log.exception(ex)
    db.session.commit()

aleph/views/sessions_api.py
import logging
from flask import session, Blueprint, redirect, request
from flask_oauthlib.client import OAuthException
from apikit import jsonify

from aleph import authz
from aleph.core import db, url_for, oauth_provider
from aleph.model import Role
from aleph.views.cache import enable_cache


log = logging.getLogger(__name__)
blueprint = Blueprint('sessions_api', __name__)


@oauth_provider.tokengetter
def get_oauth_token():
    if 'oauth' in session:
        sig = session.get('oauth')
        return (sig.get('access_token'), '')


@blueprint.before_app_request
def load_role():
    request.auth_roles = set([Role.system(Role.SYSTEM_GUEST)])
    request.auth_role = None
    request.logged_in = False

    auth_header = request.headers.get('Authorization')

    if session.get('user'):
        request.auth_roles.update(session.get('roles', []))
        request.auth_role = Role.by_id(session.get('user'))
        request.logged_in = True
    elif auth_header is not None:
        if not auth_header.lower().startswith('apikey'):
            return
        api_key = auth_header.split(' ', 1).pop()
        role = Role.by_api_key(api_key)
        if role is None:
            return
        request.auth_role = role
        request.auth_roles.update([Role.system(Role.SYSTEM_USER), role.id])
        request.logged_in = True


@blueprint.route('/api/1/sessions')
def status():
    enable_cache(vary_user=True)
    return jsonify({
        'logged_in': authz.logged_in(),
        'api_key': request.auth_role.api_key if authz.logged_in() else None,
        'role': request.auth_role,
        'roles': list(request.auth_roles),
        'permissions': {
            'collections': {
                'read': authz.collections(authz.READ),
                'write': authz.collections(authz.WRITE)
            },
            'sources': {
                'read': authz.sources(authz.READ),
                'write': authz.sources(authz.WRITE)
            }
        },
        'logout': url_for('.logout')
    })


@blueprint.route('/api/1/sessions/login')
def login():
    return oauth_provider.authorize(callback=url_for('.callback'))


@blueprint.route('/api/1/sessions/logout')
def logout():
    authz.require(authz.logged_in())
    session.clear()
    return redirect(url_for('base_api.ui'))


@blueprint.route('/api/1/sessions/callback')
def callback():
    resp = oauth_provider.authorized_response()
    if resp is None or isinstance(resp, OAuthException):
        log.warning("Failed OAuth: %r", resp)
        # FIXME: notify the user, somehow.
        return redirect(url_for('base_api.ui'))

    session['oauth'] = resp
    session['roles'] = [Role.system(Role.SYSTEM_USER)]
    if 'googleapis.com' in oauth_provider.base_url:
        me = oauth_provider.get('userinfo')
        user_id = 'google:%s' % me.data.get('id')
        role = Role.load_or_create(user_id, Role.USER, me.data.get('name'),
                                   email=me.data.get('email'))
    elif 'occrp.org' in oauth_provider.base_url or \
            'investigativedashboard.org' in oauth_provider.base_url:
        me = oauth_provider.get('api/2/accounts/profile/')
        user_id = 'idashboard:user:%s' % me.data.get('id')
        role = Role.load_or_create(user_id, Role.USER,
                                   me.data.get('display_name'),
                                   email=me.data.get('email'),
                                   is_admin=me.data.get('is_admin'))
        for group in me.data.get('groups', []):
            group_id = 'idashboard:%s' % group.get('id')
            group_role = Role.load_or_create(group_id, Role.GROUP,
                                             group.get('name'))
            session['roles'].append(group_role.id)
    else:
        raise RuntimeError("Unknown OAuth URL: %r" % oauth_provider.base_url)
    session['roles'].append(role.id)
    session['user'] = role.id
    db.session.commit()
    log.info("Logged in: %r", role)
    return redirect(url_for('base_api.ui'))

aleph/templates/alert.html
<html>
  <head>
    <style>
      body {
        font-family: sans-serif;
        font-size: 1em;
        color: #333;
      }

      a {
        color: #982022;
        font-weight: bold;
      }

      table {
        border: 0;
        width: 100%;
      }

      hr {
        margin-top: 1em;
        border: 0;
        height: 1px;
        background: #999;
      }

      p.footer {
        font-size: 0.9em;
        color: #ccc;
      }

      .source-attr a {
        color: #999;
        text-decoration: none;
      }

      tr.teaser td {
        padding-bottom: 0.5em;
        padding-left: 1em;
      }

      tr.tally-row td {
        padding-top: 1em;
      }

      em {
        background-color: yellow;
        font-style: normal;
      }
    </style>
  </head>
  <body>
    <p>Dear {{role.name}},</p>
    <p>
      new documents have been found for your alert: <strong>{{alert.label}}</strong>.
    </p>

    <table>
      {% for result in results.results %}
        <tr class="result">
          <td>
            {% if result.type == 'text' %}
              <a href="{{app_url}}#/text/{{result.id}}?{{qs}}">{{result.title}}</a>
            {% else %}
              <a href="{{app_url}}#/tabular/{{result.id}}/0?{{qs}}">{{result.title}}</a>
            {% endif %}
            <span class="source-attr">
              <a href="{{app_url}}#/search?filter:source_id={{result.source.id}}">
                {{result.source.label}}
              </a>
            </span>
          </td>
        </tr>
        <tr class="teaser">
          <td colspan="2">
            {% for rec in result.records.results %}
              {% for text in rec.text %}
                {{text | safe}}
              {% endfor %}
            {% endfor %}
          </td>
        </tr>
      {% endfor %}
      {% if results.total > 1 %}
        <tr class="tally-row">
          <td colspan="2">
            There were a total of {{results.total}} matches.
          </td>
        </tr>
      {% endif %}
    </table>

    <hr>
    <p class="footer">
      You will receive notifications like this whenever {{app_title}} adds documents that
      match your search criteria. If you would like to stop receiving them, visit
      <a href="{{app_url}}">{{app_url}}</a> to manage your active alerts.
  </body>
</html>

aleph/templates/analytics.html
{% if not config.DEBUG %}
  <!-- Piwik -->
  <script type="text/javascript">
    var _paq = _paq || [];
    _paq.push(["setDomains", ["data.occrp.org"]]);
    // _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
      var u="//piwik.occrp.org/";
      _paq.push(['setTrackerUrl', u+'piwik.php']);
      _paq.push(['setSiteId', 12]);
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
    })();
  </script>
  <noscript><p><img src="//piwik.occrp.org/piwik.php?idsite=12" style="border:0;" alt="" /></p></noscript>
  <!-- End Piwik Code -->
{% endif %}

aleph/templates/layout.html
<!DOCTYPE html>
<html lang="en" ng-app="aleph">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google" content="notranslate" />
    <title>{{config.APP_TITLE}}</title>
    
    {% assets "css" %}
      <link type="text/css" href="{{ ASSET_URL }}" rel="stylesheet">
    {% endassets %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="shortcut icon" href="{{ config.APP_FAVICON }}">
    <base href="{{url_for('.ui')}}">
  </head>
  <body ng-controller="AppCtrl">
    <div id="page" ng-show="session.roles" ng-cloak>
      <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="/#/"><img alt="{{config.APP_TITLE}}" src="{{config.APP_LOGO}}"></a>
            <a class="navbar-brand" href="/#/">{{config.APP_TITLE}}</a>
          </div>

          <div id="navbar" class="collapse navbar-collapse navbar-right">
            <ul class="nav navbar-nav">
              <li ng-show="!session.logged_in">
                <a href="{{url_for('sessions_api.login')}}" target="_self">
                  <i class="fa fa-sign-in"></i> Sign in
                </a>
              </li>
              <li ng-show="session.logged_in">
                <a ng-click="editProfile($event)">
                  <i class="fa fa-cog"></i> Settings
                </a>
              </li>
              <li ng-show="session.logged_in">
                <a ng-click="manageAlerts($event)">
                  <i class="fa fa-bell"></i> Alerts
                </a>
              </li>
              <li ng-show="session.logged_in">
                <a href="{{url_for('sessions_api.logout')}}" target="_self">
                  <i class="fa fa-sign-out"></i> Logout
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div id="spinner-overlay" ng-hide="routeLoaded">
        <div class="spinner" ng-hide="routeFailed">
          <i class="fa fa-circle-o-notch fa-spin"></i>
        </div>
        <div class="spinner failed" ng-show="routeFailed">
          <i class="fa fa-exclamation-triangle"></i>
          <div class="failure-note">
            He's dead, Jim.
          </div>
        </div>
      </div>
      <div id="view" class="container-fluid">
        <div ng-view autoscroll="true"></div>
      </div>
    </div>

    <footer>
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <p class="pull-right">
              <strong>&alefsym;</strong>
              aleph search engine &middot;
              <i class="fa fa-github-square"></i>
              <a href="https://github.com/pudo/aleph">source code</a>
            </p>
          </div>
        </div>
      </div>
    </footer>

    {% include "analytics.html" %}

    {% for path, tmpl in templates %}
      <script id="{{path}}" type="text/ng-template">{{ tmpl | safe }}</script>
    {% endfor %}

    {% assets "base" %}
      <script src="{{ ASSET_URL }}"></script>
    {% endassets %}

    {% assets "angular" %}
      <script src="{{ ASSET_URL }}"></script>
    {% endassets %}

    {% assets "app" %}
      <script src="{{ ASSET_URL }}"></script>
    {% endassets %}
  </body>
</html>